---
language: node_js
cache: npm
dist: xenial
node_js:
    - "11"

install:
    - npm install --global sass hexo-cli
    - pip install --user yamllint
    - npm install

script:
    - git lfs fetch
    - git lfs checkout
    - find -name '*.yml' -or -name '*.yaml'
        -exec yamllint -c ./development/.yamllintrc.yml '{}' +
    - shellcheck ./*.sh
    - hexo generate --verbose --debug

after_success:
    - openssl aes-256-cbc
          -K $encrypted_c0404947024a_key
          -iv $encrypted_c0404947024a_iv
          -in .travis/travis_rsa.enc
          -out .travis/travis_rsa
          -d
    - hexo deploy
