language: ruby

install:
  - gem install sass
    # lol
  - echo "downloading hugo! sorry travis' bandwidth"
  - curl https://github.com/gohugoio/hugo/releases/download/v0.38.1/hugo_0.38.1_Linux-64bit.tar.gz -L -o hugo.tar.gz
    # lol??
  - tar -xf hugo.tar.gz
    # lol, make hugo in current dir "Work"
  - export PATH=$PATH:$PWD
  - rm -rf public || exit 0

script:
  - ./post-merge.sh
  - ./check-exists.sh should-exist.txt

notifications:
    webhooks:
        urls:
            - https://becca.ooo/__travis_webhook__
        # this is used for deploying the site; we don't want failures to build
        on_success: always # default: always
        on_failure: never # default: always
        on_start: never   # default: never
        on_cancel: never  # default: always
        on_error: never   # default: always
