---
language: node_js
cache: npm
dist: xenial
node_js:
    - "11"

install:
    - npm install --global sass
    - pip install --user yamllint
    - >
        curl
        https://github.com/gohugoio/hugo/releases/download/v0.55.0/hugo_0.55.0_Linux-64bit.tar.gz
        -L -o hugo.tar.gz
    - tar -xf hugo.tar.gz
    - export PATH=$PATH:$PWD
    - rm -rf public || exit 0

script:
    - ./post-merge.sh
    - find -name '*.yml' -or -name '*.yaml' -exec yamllint -c ./.yamllintrc.yml '{}' +
    - ./check-exists.sh should-exist.txt
    - shellcheck ./*.sh

notifications:
    webhooks:
        urls:
            - https://becca.ooo/__travis_webhook__
        # this is used for deploying the site; we don't want failures to build
        on_success: always  # default: always
        on_failure: never   # default: always
        on_start: never     # default: never
        on_cancel: never    # default: always
        on_error: never     # default: always
