baseURL="https://becca.ooo/"
title="rebecca t"
ignoreFiles=["static/(img/reel|i-c-the-light|chomp|juniorportfolio)"]

DefaultContentLanguage="en"
disableKinds=[
	"taxonomy",
	"taxonomyTerm",
	"RSS",
	"404"
]

# delete taxonomies
[taxonomies]
